NORTH_AMERICA = [
    "aws.amazon.com",
    "cloudflare.com",
    "cogentco.com",
    "data.gov",
    "defense.gov",
    "digitalrealty.com",
    "digitalrealty.com",
    "dominicana.gob.do",
    "equinix.com",
    "equinix.com",
    "fema.gov",
    "gob.hn",
    "gob.mx",
    "gob.sv",
    "govinfo.gov",
    "guatemala.gob.gt",
    "house.gov",
    "irs.gov",
    "microsoft.com",
    "presidencia.go.cr",
    "presidencia.gob.ni",
    "presidencia.gob.pa",
    "shopify.com",
    "ssa.gov",
    "supremecourt.gov",
    "usa.gov",
    "usa.gov",
]

SOUTH_AMERICA = [
    "argentina.gob.ar",
    "gob.cl",
    "gob.pe",
    "gob.ve",
    "gobernacion.gob.bo",
    "google.com.br",
    "gov.br",
    "gov.co",
    "gub.uy",
    "presidencia.gob.ec",
    "presidencia.gob.py",
    "shopify.com.br",
    "sis.sig.uema.br",
    "ufba.br",
    "ufc.br",
    "ufpr.br",
    "usach.cl",
]

EUROPE = [
    "admin.ch",
    "ams-ix.net",
    "atlasedge.com",
    "belgium.be",
    "bundeskanzleramt.gv.at",
    "bundesregierung.de",
    "bundesregierung.de",
    "data4group.com",
    "de-cix.net",
    "govern.ad",
    "government.by",
    "government.nl",
    "government.ru",
    "gouv.mc",
    "gouvernement.fr",
    "gouvernement.lu",
    "gov.bg",
    "gov.cy",
    "gov.ie",
    "gov.md",
    "gov.me",
    "gov.pl",
    "gov.ro",
    "gov.sm",
    "gov.uk",
    "gov.uk",
    "kmu.gov.ua",
    "knu.ua",
    "kormany.hu",
    "lamoncloa.gob.es",
    "merlinproperties.com",
    "mk.gov.lv",
    "nabiax.com",
    "ovh.com",
    "primeminister.gr",
    "regjeringen.no",
    "srbija.gov.rs",
    "startcampus.pt",
    "stm.dk",
    "up.pt",
    "valitsus.ee",
    "valtioneuvosto.fi",
    "vatican.va",
    "vijeceministara.gov.ba",
    "vlada.cz",
    "vlada.gov.hr",
    "vlada.gov.sk",
    "vlada.mk",
    "yandex.ru",
]

AFRICA = [
    "africadatacentres.com",
    "cu.edu.eg",
    "mdxi.mainone.net",
    "paix.io",
    "rack-centre.com",
    "uct.ac.za",
]

ASIAN = [
    "baidu.com",
    "english.pku.edu.cn",
    "gov.am",
    "gov.ge",
    "gov.il",
    "gov.kz",
    "hk01.com",
    "india.gov.in",
    "jio.com",
    "jpnap.net",
    "mea.gov.in",
    "naver.com",
    "rakuten.co.jp",
    "services.global.ntt",
    "sgix.sg",
    "shopee.sg",
    "shopee.tw",
    "tccb.gov.tr",
    "u.ae",
    "ud.ac.ae",
]

OCEANIA = [
    "anu.edu.au",
    "ato.gov.au",
    "unimelb.edu.au",
    "xtra.co.nz",
]

UNKNOWN = [
    "developers.omnicomm-world.com",
    "servicedocs.marinetraffic.com",
]

TARGETS = (
    NORTH_AMERICA + SOUTH_AMERICA + EUROPE + AFRICA + ASIAN + OCEANIA + UNKNOWN
)
